### ISSUE TITLE
Action to Generate Additional Domino Server ID

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Installer#124]
From @JustinProminic

>14:14:08: ok.   and have you and Mark gotten the instructions and command line script for registering a new server and registering a new user ID, so we can use SHI to create first server in first domain, then the CLI tools to register aditional user/server, then download the ID back to the host, then use SHI to create on the same machine the second server to join the existing server?  for SHI I think that is what we should target next to have that done.
>14:28:47: doing what I just described - making it available for people to test creating fresh domains and adding additional fresh servers to the fresh domain -- remains a key undelivered goal of SHI that we need to close the gap on.  this would allow for a lot of testing that we just cannot do right now without getting these steps fully done.

This is is a key part of the additional Domino server support (#85).  This will be based on the CreateAdditionalServerID class that was added to the provisioners [here](https://github.com/STARTcloud/hcl_roles/issues/10) (pending testing).

The current process is (TODO:  report manual test):
0. Requires a local standalone or additional Domino instance for the same Domino organization
1. Create or deploy CrossCertifyNotesID.properties in the instance  (/local/notesjava? Setup an independent directory?)
2. SSH to the instance and navigate to the above directory as `java_user`
3. Run java -jar CreateAdditionalServerID.jar
4. SCP the generated ID file (based on CrossCertifyNotesID.properties?) to the local machine
5. Create a new additional server instance and provide the generated ID file

The proposed process would be something like this:
1. Select a local instance that shares the desired organization. Note that this must be using the updated provisiones
2. Click Create Additional Server
3. Fill in a form.  Some information should be populated from the original server
4. Generate the ID
    1. Generate CrossCertifyNotesID.proeprties based on the form input
    2. Deploy CrossCertifyNotesID.proeprties to the instance
    3. Run CreateAdditionalServerID.jar with the properties file
    4. Pull the ID file back to a temporary location on the local host
5. Open the form to create a new Additional Domino instance and populate it with the entered information

TODO: 
- Finish testing the [provisioner updates](https://github.com/STARTcloud/hcl_roles/issues/10)
- Release 0.1.23 provisioner with the CreateAdditionalServerID logic.   We can test these provisioners manually in the meantime
- Make the instructions above more explicit (paths, format for JSON file)

**Comment by JoelProminic** [comment]
@MarkProminic created the additional server provisioners [here](https://github.com/STARTcloud/hcl_domino_additional_provisioner).

@MarkProminic had created an MXHX mockup for the additional server interface in MXHX - we will attach it to the issue if we find it.  However, I would expect the UI fields too still look similar to my writeup [here](https://github.com/Moonshine-IDE/Super.Human.Installer/issues/85#issuecomment-2224081131)

The next step is to review thew new [SHI-Hosts.yml template](https://github.com/STARTcloud/hcl_domino_additional_provisioner/blob/main/hcl_domino_additional_provisioner/templates/SHI-Hosts.yml) and:
- Ensure the template is working and up-to-date after the recent refactorings
- Map the above fields to the insertion parameters
- Identify any additional insertion parameters that need to be populated.

I am planning to revisit hcl_domino_additional_provisioner in the next couple days while I wrap up some work for #124, so I can help with this if someone else doesn't get to it first.

**Comment by JoelProminic** [comment]
For future reference, here are the previous commands:

>UPDATE:  Here are the commands I used in a real test (not including creating the additional server
>```
>    vagrant ssh
>    sudo su - java_user
>    bash
>    mkdir /tmp/additional
>
>    # Create  /tmp/additional/additional.properties
>    server.name=test-additional.shi.com
>    server.id.password=password
>    server.id.title=test-additional.shi.com
>    server.id.output=/tmp/additional/test-additional.shi.com.id
>
>    java -jar /local/notesjava/CreateAdditionalServerID.jar /tmp/additional/additional.properties
>```
>With this configuration (server.id.output), the generated ID file is found at: /tmp/additional/test-additional.shi.com.id

However, this solution didn't work because:
- Setting a password on the ID file causes trouble for Domino installation, the Nashed service, and JeDI
- Removing the error triggers an error, and I could not work around it with the API

@feather812002 created a version with a different API.  This works but it has very specific requirements:
- Must run as the `domino` user, rather than `java_user`. Note that LD_LIBRARY_PATH needs to be set
- Must run in in the `/local/notesdata` directory

```
$ sudo vim /local/notesdata/additional.properties
server.name=test-additional.shi.com
server.id.password=
server.id.title=test-additional.shi.com
server.id.output=/tmp/test-additional.shi.com.id
$ sudo -u domino env LD_LIBRARY_PATH="/opt/hcl/domino/notes/latest/linux" java -jar CreateAdditionalServerJNA.jar additional.properties 
```

This also works:

```
$ sudo su - domino
$ export LD_LIBRARY_PATH="/opt/hcl/domino/notes/latest/linux"
$ java -jar CreateAdditionalServerJNA.jar additional.properties 
```

**Comment by JoelProminic** [comment]
@piotrzarzycki21, was this implemented?   This issue is for Super.Human.Installer generating the Additional Server ID in an automated fashion, using the [tools I created in a previous release](https://github.com/STARTcloud/hcl_roles/issues/10).  Additional Domino Server support (with the user providing the ID) was added in release 1.1.0 (#85).

If thiis was implemented, point me to where I can test this.   Otherwise, this should be bumped to 1.5.0.

**Comment by MarkProminic** [comment]
To expose this on in the GUI, I think that we should implement a what some of know interally as the "SSH Operations Manager" in SHI instead of relying on the Hosts.rb to do all of this.

@https://github.com/Moonshine-IDE/Super.Human.Installer/issues/162

I think this issue will lay the foundation for being able to issue commands in the VM directly from SHI (assuming its provisioned)

**Comment by JoelProminic** [comment]
We revisited this in the Wednesday meeting for testing ReplicaChecker.  @piotrzarzycki21, here is an example of the additional server setup:

I created a server like this:

<img width="699" height="155" alt="Image" src="https://github.com/user-attachments/assets/875cd419-5716-40f4-af0c-163b696e5866" />

Then SSHed to the server and ran these commands

```
startcloud@test-1a:~$ sudo su - domino
$ bash
domino@test-1a:~$ vim /tmp/additional.properties
domino@test-1a:~$ cat /tmp/additional.properties 
server.name=test-1a-add.testreplicachecker.com
server.id.password=
server.id.title=test-1a-add.testreplicachecker.com
server.id.output=/tmp/test-1a-add.testreplicachecker.com.id
domino@test-1a:~$ pwd
/local/notesdata
domino@test-1a:~$ cp /local/notesjava/CrossCertifyNotesID.properties .
domino@test-1a:~$ export LD_LIBRARY_PATH="/opt/hcl/domino/notes/latest/linux"
domino@test-1a:~$ java -jar /local/notesjava/CreateAdditionalServerJNA.jar /tmp/additional.properties 
Application 'CreateAdditionalServerJNA' started.
	(debug)propertiesFileName='null'.
Loading properties file '/local/notesdata/CrossCertifyNotesID.properties'.
Loading additional server properties:  '/tmp/additional.properties'.
additionalServerPassword len: 0
Initializing Domino JNA
Additional Server Name: test-1a-add.testreplicachecker.com
Additional Server Title: test-1a-add.testreplicachecker.com
hostServerIDFilePath: /local/notesdata/server.id
addtionalServerIDStorePath: /tmp/test-1a-add.testreplicachecker.com.id
Switched to ID: /local/notesdata/server.id:CN=test-1a.testreplicachecker.com/O=TESTRC1
session username: CN=test-1a.testreplicachecker.com/O=TESTRC1
Getting certifier context from: /local/notesdata/cert.id
Server registration completed successfully
Application 'CreateAdditionalServerJNA' completed.
domino@test-1a:~$ grep server.id.output /tmp/additional.properties 
server.id.output=/tmp/test-1a-add.testreplicachecker.com.id
domino@test-1a:~$ exit
exit
$ exit
startcloud@test-1a:~$ sudo chown startcloud:startcloud /tmp/test-1a-add.testreplicachecker.com.id
# Get the IP address for later
startcloud@test-1a:~$ ip address
...
3: public_adapter: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:9b:1d:84 brd ff:ff:ff:ff:ff:ff
    inet 10.0.14.19/24 metric 100 brd 10.0.14.255 scope global dynamic public_adapter
       ...
# The IP here is 10.0.14.19
```

Then open FileZilla SCP from SHI and SCP this file:   /tmp/test-1a-add.testreplicachecker.com.id

Alternatively, you can use this command: `vagrant scp :/tmp/test-1a-add.testreplicachecker.com.id ~/Downloads/`

Then create a new additional server like this:
- Get Hostname from the /tmp/additional.properties file
- New server ID file should be the ID that you copied
- Use the same Domino version you used for the original VM.

<img width="676" height="472" alt="Image" src="https://github.com/user-attachments/assets/9675e0ed-19cc-402d-bb2a-995e0d644306" />


UPDATE: With Mark's fix for #180, I was able to create an additional server.

To confirm the result, run this on the standalone server:

```
# Add a hosts file entry for the new server.  Get the IP from results.yml or from `ip address`
echo "10.0.14.21 test-1a-add.testreplicachecker.com" | sudo tee -a /etc/hosts
sudo su - java_user
java -jar CheckDatabase.jar test-1a-add.testreplicachecker.com names.nsf
# The password is 'password'
```

**Comment by JoelProminic** [comment]
@piotrzarzycki21, unfortunately I was not able to save the server configuration in the last step. I created #180 to track this error.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I will investigate this on my own slowly but just FYI I got following error: 

```
sudo su - domino
$ pwd 
/local/notesdata
$ cp /local/notesjava/CrossCertifyNotesID.properties .
$ export LD_LIBRARY_PATH="/opt/hcl/domino/notes/latest/linux"
$ java -jar /local/notesjava/CreateAdditionalServerJNA.jar /tmp/additional.properties
Application 'CreateAdditionalServerJNA' started.
	(debug)propertiesFileName='null'.
Loading properties file '/local/notesdata/CrossCertifyNotesID.properties'.
java.io.FileNotFoundException: /local/notesdata/setup.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at net.prominic.domino.vagrant.CreateAdditionalServerJNA.main(CreateAdditionalServerJNA.java:57)
Application 'CreateAdditionalServerJNA' completed.
$ 
```

**Comment by piotrzarzycki21** [comment]
@MarkProminic It sounds after provisioning this file setup.json is [being removed](https://github.com/Moonshine-IDE/Super.Human.Installer/blob/f6965f6768acf0bfcadd01f36b9b0844890e85a2/Assets/provisioners/hcl_domino_standalone_provisioner/0.1.24/provisioners/ansible_collections/startcloud/hcl_roles/roles/domino_config/tasks/main.yml#L395). Is it something which you have to fix potentially ?

**Comment by JoelProminic** [comment]
If I remember correctly, the related option is "Clean up Debug files"

<img width="727" height="143" alt="Image" src="https://github.com/user-attachments/assets/baf36c64-9b95-4325-a872-3221d00e8773" />

I have some instructions to replace setup.json [here](https://github.com/Moonshine-IDE/Super.Human.Installer/issues/167#issue-3271407207).   I'll check if something else is needed for CreateAdditionalServerJNA

UPDATE:  This should be what you need:
- certifierPassword - use "password" unless you specifically changed this.
- name and domainName - update these to match your instance.  This configuration matches the source VM I used [here](https://github.com/Moonshine-IDE/Super.Human.Installer/issues/124#issuecomment-3862924429)


```
{
  "serverSetup": {
    "server": {
      "name": "test-1a.testreplicachecker.com",
      "domainName": "TESTRC1"
    },
    "org": {
      "certifierPassword": "password"
    }
  }
}

```

UPDATE:  "name" should match the "Hostname" of the original instance, and "domainName" should match "Organizational Certifier".  You can also get these directly from the server list:
<img width="735" height="159" alt="Image" src="https://github.com/user-attachments/assets/92a489fb-6c8c-4492-897d-b8a3d7187256" />

UPDATE:  this is how `lockdown_cleanup_debug_files` is set in Hosts.yml:

```
      ## Lockdown Variables
      lockdown_cleanup_debug_files: false
...
      - name: startcloud.startcloud_roles.lockdown
        when: true

```

**Comment by JoelProminic** [comment]
I added a note for testing the additional server to the instructions [here](https://github.com/Moonshine-IDE/Super.Human.Installer/issues/124#issuecomment-3862924429).

Note that if you try the same commands with a standalone server, you will get an error like this:  

```
java_user@test-1a:~$ java -jar CheckDatabase.jar test-standalone.shi.com names.nsf
Running on Notes Version: 'Release 14.5|June 06, 2025             '.
[024935:000002-00007F04F13FF6C0] 02/09/2026 12:54:05.21 PM AuthInitialize> SECMngPortEncSettingConfig init failure 0x0103
[024935:000002-00007F04F13FF6C0] The ID file being used is: /local/notesdata/ids/admin-user.id
[024935:000002-00007F04F13FF6C0] Enter password (press the Esc key to abort): 

FAILED!
java.lang.Exception: Unable to open server 'test-standalone.shi.com': 'Directory test-standalone.shi.com!! does not exist'.
	at net.prominic.domino.vagrant.CheckDatabase.checkServer(CheckDatabase.java:99)
	at net.prominic.domino.vagrant.CheckDatabase.main(CheckDatabase.java:43)
java_user@test-1a:~$ 
```

And the target server console will show the actual error (cross-certification):

```
[001147:000084-00007FE03DB366C0] 02/09/2026 12:54:16 PM  Prominic Admin/TESTRC1 from host [10.0.14.19:46315] failed to authenticate: The server's Domino Directory does not contain any cross certificates capable of authenticating you.
```

**Comment by MarkProminic** [comment]
@piotrzarzycki21  are you saying that if you have the Cleanup Debug files set to FALSE( ie greyed out like so 

<img width="727" height="143" alt="Image" src="https://github.com/user-attachments/assets/88529211-65bf-477a-98a7-782ad34a1ada" />) 

That its deleting the file setup.json?

**Comment by piotrzarzycki21** [comment]
> [@piotrzarzycki21](https://github.com/piotrzarzycki21) are you saying that if you have the Cleanup Debug files set to FALSE( ie greyed out like so
> 
> <img alt="Image" width="727" height="143" src="https://private-user-images.githubusercontent.com/50398495/547299582-88529211-65bf-477a-98a7-782ad34a1ada.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzA3MzIxNjUsIm5iZiI6MTc3MDczMTg2NSwicGF0aCI6Ii81MDM5ODQ5NS81NDcyOTk1ODItODg1MjkyMTEtNjViZi00NzdhLTk4YTctNzgyYWQzNGExYWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjEwVDEzNTc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMjQyMTllYjlkNDcwMmE4ZTliZjU5M2MyNWIwZGJjMWQzZjJjMGFjMTliNjdjY2ZhMDY3NjRkOTVjNjZmMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WeinJcJCdwKXgO_PgppiwCiU9tom3WTkx5LyEIcRAHs">)
> 
> That its deleting the file setup.json?

@MarkProminic It hard to say what was set, because I have created this server a while ago. Let me know which opt in created server is responsible for above settings ?

**Comment by piotrzarzycki21** [comment]
> }

@JoelProminic Unfortunately I don't understand what should I put in domainName ?

**Comment by piotrzarzycki21** [comment]
I'm a bit farther. I have used provisioner 0.1.24 for additional server, but it failed. I will try with 0.1.24. Meanwhile @MarkProminic  this is the results: 


```
---- Hosts.yml END ----
[SHI]: VirtualBox VM: [virtualBoxId => 6778--mars-add.startcloud.com]
[SHI]: Executing 'vagrant up' (provision:false)
Checking for vagrant-scp-sync plugin...vagrant-scp-sync (0.5.29, global)
vagrant-scp-sync plugin already installed[SHI]: 'vagrant up' started
Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.

Path: /opt/vagrant/embedded/gems/gems/vagrant-2.4.9/plugins/kernel_v2/config/vm.rb
Line number: 0
Message: undefined method `to_sym'
[SHI]: 'vagrant up' stopped with exit code: 1, elapsed time: 00:00:02
```

**Comment by piotrzarzycki21** [comment]
It went quite far, but failed. Not sure what Happened, nothing specific is there: 

```
TASK [startcloud.hcl_roles.domino_config : Configuring Domino server via setup.json] ***
[0;33mchanged: [4814--mars-add.startcloud.com] => (item=(su - domino -c '/opt/hcl/domino/bin/server -autoconf setup.json && touch /vagrant/completed/domsetup  > /dev/null 2>&1 &'))[0m
[0;32m [started TASK: startcloud.hcl_roles.domino_config : Waiting until the file autoconfigure.log is present before continuing on 4814--mars-add.startcloud.com][0m

TASK [startcloud.hcl_roles.domino_config : Waiting until the file autoconfigure.log is present before continuing] ***
[0;32mok: [4814--mars-add.startcloud.com][0m
[0;32m [started TASK: startcloud.hcl_roles.domino_config : Waiting for 'Application configuration completed successfully' in Autoconfigure on 4814--mars-add.startcloud.com][0m

TASK [startcloud.hcl_roles.domino_config : Waiting for 'Application configuration completed successfully' in Autoconfigure] ***
[1;30mtask path: /vagrant/ansible_collections/startcloud/hcl_roles/roles/domino_config/tasks/main.yml:230[0m
[0;31mfatal: [4814--mars-add.startcloud.com]: FAILED! => changed=false [0m
[0;31m  elapsed: 300[0m
[0;31m  msg: Timeout when waiting for search string Application configuration completed successfully in /local/notesdata/IBM_TECHNICAL_SUPPORT/autoconfigure.log[0m

PLAY RECAP *********************************************************************
[0;31m4814--mars-add.startcloud.com[0m : [0;32mok=228 [0m [0;33mchanged=117 [0m unreachable=0    [0;31mfailed=1   [0m [0;36mskipped=97  [0m rescued=0    ignored=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
[SHI]: 'vagrant up' stopped with exit code: 1, elapsed time: 00:36:26
```

**Comment by JoelProminic** [comment]
This could just be slow, but you should check `/local/notesdata/IBM_TECHNICAL_SUPPORT/autoconfigure.log` if you still have access.  This could indicate a problem with the vars.  I see an example [here](https://github.com/Moonshine-IDE/Super.Human.Installer/issues/85#issuecomment-2672557332).

**Comment by MarkProminic** [comment]
0.1.24 was added to because I had been working on it, but Joel needed the
fixes to get it to save at all. So I had to just push it out.

Please use 0.1.23

**Comment by JoelProminic** [comment]
> > }
> 
> [@JoelProminic](https://github.com/JoelProminic) Unfortunately I don't understand what should I put in domainName ?

I added some clarification to the writeup [here](https://github.com/Moonshine-IDE/Super.Human.Installer/issues/124#issuecomment-3873204058)

**Comment by JoelProminic** [comment]
@piotrzarzycki21 asked about updating the hosts file.   I had written up something for this, but it seems it didn't update properly on the issue.

>With Mark's fix for #180, I was able to create an additional server.
>
>To confirm the result, run this on the standalone server:
>
>```
># Add a hosts file entry for the new server.  Get the IP from results.yml or from `ip address`
>echo "10.0.14.21 test-1a-add.testreplicachecker.com" | sudo tee -a /etc/hosts
>sudo su - java_user
>java -jar CheckDatabase.jar test-1a-add.testreplicachecker.com names.nsf
># The password is 'password'
>```

I added this to the [main instructions](https://github.com/Moonshine-IDE/Super.Human.Installer/issues/124#issuecomment-3862924429)
